name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache downloads
      uses: actions/cache@v1
      with:
        path: dl/
        key: dl
    - name: Update submodules
      run: git submodule update --init
    - name: Compile
      run: |
        apt install python-dev
        cd buildroot
        make BR2_EXTERNAL=$PWD/.. linuxcard_defconfig
        make
    - uses: actions/upload-artifact@v1
      with:
        name: flash.bin
        path: buildroot/output/images/flash.bin
